package com.haoo.iframe.errcode;

/**
 * {@code ApiCode}定义异常 code 和 异常 message 信息
 *
 * @Package: cn.echo.enterprise.errcode
 * @Author: pluto
 * @CreateTime: 2021/10/26 3:50 下午
 * @Description: 异常类型
 **/
public enum ApiCode {

    /**
     * 已分配，待统一de系统使用的错误码，过时
     */
    SUCCESS(200, "操作成功"),
    UNAUTHORIZED(401, "非法访问"),
    NOT_PERMISSION(403, "没有权限"),
    NOT_FOUND(404, "你请求的资源不存在"),
    IS_FOUND(100, "请求资源已存在"),
    FAIL(500, "操作失败"),
    LOGIN_EXCEPTION(4000, "登录失败"),
    LOGIN_EXCEPTION_WRONG_ACCOUNT_OR_PASSWORD(4001, "用户名或密码错误"),
    REQUEST_DATA_FORMAT_NOT_AVAILABLE(4098, "经检查，您的输入信息中有些数据不符合格式要求，请使用合理的数据格式！具体原因请查看[data]"),
    SYSTEM_EXCEPTION_DATA(4099, "异常！具体原因请查看[data]"),
    SYSTEM_EXCEPTION(5000, "系统异常"),
    PARAMETER_EXCEPTION(5001, "请求参数校验异常"),
    PARAMETER_PARSE_EXCEPTION(5002, "请求参数解析异常"),
    HTTP_MEDIA_TYPE_EXCEPTION(5003, "HTTP内容类型异常"),
    SPRING_BOOT_PLUS_EXCEPTION(5100, "系统处理异常"),
    BUSINESS_EXCEPTION(5101, "业务处理异常"),
    DAO_EXCEPTION(5102, "数据库处理异常"),
    VERIFICATION_CODE_EXCEPTION(5103, "验证码校验异常"),
    AUTHENTICATION_EXCEPTION(5104, "登录授权异常"),
    UNAUTHENTICATED_EXCEPTION(5105, "没有访问权限"),
    UNAUTHORIZED_EXCEPTION(5106, "没有访问权限"),
    TOKEN_NOT_EMPTY(5107, "token不存在"),
    TOKEN_EXPIRED(5109, "token失效"),
    UNABLE_TO_DELETE(5110, "无法删除"),
    SELECT_THE_SUPERIOR_LIST(5111, "请选择上级列表"),
    HTTP_REQUEST_METHOD_NOT_SUPPORTED_EXCEPTION(5108, "METHOD NOT SUPPORTED"),


    /**
     *
     * 定义参考的错误码，按细分程度分A/B/C级错误码
     *
     * 用户端错误，1****
     * 系统执行出错，5****
     * 调用第三方服务出错，7****
     */
    /**
     * 正确执行后的返回
     */
    OK(00000, "一切ok"),
    /**
     * 用户端-A级错误码
     */
    CLIENT_A_COMMON(10001, "用户端错误"),
    /**
     * 用户端-B级错误码
     */
    CLIENT_B_REGISTERED_ERROR(10100, "用户注册错误"),
    CLIENT_B_UNAGREED_PRIVACY_AGREEMENT(10101, "用户未同意隐私协议"),
    CLIENT_B_REGISTERED_COUNTRY_OR_REGION_LIMITED(10102, "注册国家或地区受限"),
    CLIENT_B_USERNAME_CHECKED_FAILURE(10110, "用户名校验失败"),
    CLIENT_B_USERNAME_EXISTED(10111, "用户名已存在"),
    CLIENT_B_USERNAME_CONTAINS_SENSITIVE_WORDS(10112, "用户名包含敏感词"),
    CLIENT_B_USERNAME_CONTAINS_SPECIAL_CHARACTERS(10113, "用户名包含特殊字符"),
    CLIENT_B_PASSWORD_CHECKED_FAILURE(10120, "密码校验失败"),
    CLIENT_B_PASSWORD_LENGTH_INSUFFICIENT(10121, "密码长度不够"),
    CLIENT_B_PASSWORD_NOT_ENOUGH(10122, "密码强度不够"),
    CLIENT_B_CHECK_CODE_ERROR(10130, "校验码输入错误"),
    CLIENT_B_CHECK_CODE_ERROR_SMS(10131, "短信校验码输入错误"),
    CLIENT_B_CHECK_CODE_ERROR_MAIL(10132, "邮件校验码输入错误"),
    CLIENT_B_CHECK_CODE_ERROR_VOICE(10133, "语音校验码输入错误"),
    CLIENT_B_USER_CERTIFICATE_EXCEPTION(10140, "用户证件异常"),
    CLIENT_B_USER_CERTIFICATE_TYPE_IS_NOT_SELECTED(10141, "用户证件类型未选择"),
    CLIENT_B_USER_CERTIFICATE_ID_NUMBER_IS_ILLEGAL(10142, "大陆身份证编号校验非法"),
    CLIENT_B_USER_PASSPORT_NUMBER_IS_ILLEGAL(10143, "护照编号校验非法"),
    CLIENT_B_USER_MILITARY_CERTIFICATE_IS_ILLEGAL(10144, "军官证编号校验非法"),
    CLIENT_B_USER_BASIC_INFO_CHECKED_FAILURE(10150, "用户基本信息校验失败"),
    CLIENT_B_PHONE_FORMAT_IS_ILLEGAL(10151, "手机格式校验失败"),
    CLIENT_B_ADDRESS_FORMAT_IS_ILLEGAL(10152, "地址格式校验失败"),
    CLIENT_B_MAIL_FORMAT_IS_ILLEGAL(10153, "邮箱格式校验失败"),
    /**
     * 用户端-B级错误码
     */
    CLIENT_B_USER_LOGIN_EXCEPTION(10200, "用户登录异常"),
    CLIENT_B_USER_ACCOUNT_NOT_EXIST(10201, "用户账户不存在"),
    CLIENT_B_USER_ACCOUNT_IS_FROZEN(10202, "用户账户被冻结"),
    CLIENT_B_USER_ACCOUNT_HAS_BEEN_INVALIDATED(10203, "用户账户已作废"),
    CLIENT_B_USER_PASSWORD_ERROR(10210, "用户密码错误"),
    CLIENT_B_USER_INPUT_PASSWORD_IS_OVER_TRIED(10211, "用户输入密码错误次数超限"),
    CLIENT_B_USER_IDENTITY_CHECKED_FAILURE(10220, "用户身份校验失败"),
    CLIENT_B_USER_FINGERPRINT_FAILURE(10221, "用户指纹识别失败"),
    CLIENT_B_USER_FACE_RECOGNITION_FAILURE(10222, "用户面容识别失败"),
    CLIENT_B_USER_NOT_OBTAIN_THE_THIRD_PARTY_LOGIN_AUTHORIZATION(10223, "用户未获得第三方登录授权"),
    CLIENT_B_USER_LOGIN_HAS_EXPIRED(10230, "用户登录已过期"),
    CLIENT_B_USER_CHECK_CODE_ERROR(10240, "用户验证码错误"),
    CLIENT_B_USER_CHECK_CODE_IS_OVER_TRIED(10241, "用户验证码尝试次数超限"),
    /**
     * 用户端-B级错误码
     */
    CLIENT_B_ACCESS_EXCEPTION(10300, "访问权限异常"),
    CLIENT_B_ACCESS_UNAUTHORIZED(10301, "访问未授权"),
    CLIENT_B_ACCESS_UNDER_AUTHORIZATION(10302, "正在授权中"),
    CLIENT_B_ACCESS_AUTHORIZATION_IS_REJECTED(10303, "用户授权申请被拒绝"),
    CLIENT_B_ACCESS_INTERCEPTED_BY_THE_PRIVACY_SETTINGS(10310, "因访问对象隐私设置被拦截"),
    CLIENT_B_ACCESS_AUTHORIZATION_EXPIRED(10311, "授权已过期"),
    CLIENT_B_ACCESS_UNAUTHORIZED_LIMIT(10312, "无权限使用1PI"),
    CLIENT_B_ACCESS_IS_INTERCEPTED(10320, "用户访问被拦截"),
    CLIENT_B_ACCESS_ACCOUNT_IS_BLACKLIST_USER(10321, "黑名单用户"),
    CLIENT_B_ACCESS_ACCOUNT_IS_FROZEN(10322, "账号被冻结"),
    CLIENT_B_ACCESS_LIMITED_AS_ILLEGAL_IP_ADDRESS(10323, "非法IP地址"),
    CLIENT_B_ACCESS_LIMITED_AS_GATEWAY_ACCESS_IS_LIMITED(10324, "网关访问受限"),
    CLIENT_B_ACCESS_LIMITED_AS_GEOGRAPHIC_BLACKLIST(10325, "地域黑名单"),
    CLIENT_B_ACCESS_LIMITED_AS_SERVICE_OVERDUE(10330, "服务已欠费"),
    CLIENT_B_ACCESS_LIMITED_AS_USER_SIGNATURE_EXCEPTION(10340, "用户签名异常"),
    CLIENT_B_ACCESS_LIMITED_AS_RS1_SIGNATURE_ERROR(10341, "RS1签名错误"),
    /**
     * 用户端-B级错误码
     */
    CLIENT_B_PARAMETER_ERROR(10400, "用户请求参数错误"),
    CLIENT_B_PARAMETER_INCLUDE_MALICIOUS_ILLEGAL_JUMP_LINKS(10401, "包含非法恶意跳转链接"),
    CLIENT_B_PARAMETER_INPUT_INVALID_(10402, "无效的用户输入"),
    CLIENT_B_PARAMETER_REQUIRED_IS_EMPTY(10410, "请求必填参数为空"),
    CLIENT_B_PARAMETER_ORDER_NUMBER_IS_EMPTY(10411, "用户订单号为空"),
    CLIENT_B_PARAMETER_QUANTITY_ORDERED_IS_EMPTY(10412, "订购数量为空"),
    CLIENT_B_PARAMETER_TIMESTAMP_IS_EMPTY(10413, "缺少时间戳参数"),
    CLIENT_B_PARAMETER_ILLEGAL_TIMESTAMP(10414, "非法的时间戳参数"),
    CLIENT_B_PARAMETER_VALUE_EXCEEDED(10420, "请求参数值超出允许的范围"),
    CLIENT_B_PARAMETER_FORMAT_MISMATCH(10421, "参数格式不匹配"),
    CLIENT_B_PARAMETER_ADDRESS_NOT_IN_SERVICE_SCOPE(10422, "地址不在服务范围"),
    CLIENT_B_PARAMETER_TIME_NOT_IN_SERVICE_SCOPE(10423, "时间不在服务范围"),
    CLIENT_B_PARAMETER_AMOUNT_EXCEEDED_LIMIT(10424, "金额超出限制"),
    CLIENT_B_PARAMETER_QUANTITY_EXCEEDED_LIMIT(10425, "数量超出限制"),
    CLIENT_B_PARAMETER_BATCH_EXCEEDED_LIMIT(10426, "请求批量处理总个数超出限制"),
    CLIENT_B_PARAMETER_JSON_PARSING_FAILURE(10427, "请求JSON解析失败"),
    CLIENT_B_PARAMETER_INPUT_ILLEGAL(10430, "用户输入内容非法"),
    CLIENT_B_PARAMETER_CONTAINS_SENSITIVE_WORDS(10431, "包含违禁敏感词"),
    CLIENT_B_PARAMETER_PHOTO_CONTAINS_SENSITIVE_INFO(10432, "图片包含违禁信息"),
    CLIENT_B_PARAMETER_FILE_COPYRIGHT_INFRINGEMENT(10433, "文件侵犯版权"),

    CLIENT_B_OPERATING_EXCEPTION(10440, "用户操作异常"),
    CLIENT_B_OPERATING_PAYMENT_TIMEOUT(10441, "用户支付超时"),
    CLIENT_B_OPERATING_ORDER_CONFIRMATION_TIMEOUT(10442, "确认订单超时"),
    CLIENT_B_OPERATING_ORDER_CLOSED(10443, "订单已关闭"),

    /**
     * 用户端-B级错误码
     */
    CLIENT_B_REQUEST_EXCEPTION(10500, "用户请求服务异常"),
    CLIENT_B_REQUEST_EXCEEDED_LIMIT(10501, "请求次数超出限制"),
    CLIENT_B_REQUEST_CONCURRENT_NUMBER_EXCEEDED_LIMIT(10502, "请求并发数超出限制"),
    CLIENT_B_REQUEST_WAITING_FOR_USER_OPERATION(10503, "用户操作请等待"),
    // We5So4ket连接异常
    CLIENT_B_REQUEST_CONNECTION_EXCEPTION(10504, "连接异常"),
    // We5So4ket连接断开
    CLIENT_B_REQUEST_CONNECTION_DISCONNECTED(10505, "连接断开"),
    CLIENT_B_REQUEST_REPEATED(10506, "用户重复请求"),

    /**
     * 用户端-B级错误码
     */
    CLIENT_B_RESOURCE_EXCEPTION(10600, "用户资源异常"),
    CLIENT_B_RESOURCE_OUT_OF_BALANCE(10601, "账户余额不足"),
    CLIENT_B_RESOURCE_NOT_ENOUGH_DISK_SPACE(10602, "用户磁盘空间不足"),
    CLIENT_B_RESOURCE_NOT_ENOUGH_MEMORY(10603, "用户内存空间不足"),
    CLIENT_B_RESOURCE_NOT_ENOUGH_OSS_CAPACITY(10604, "用户OSS容量不足"),
    CLIENT_B_RESOURCE_NOT_ENOUGH_QUOTA(10605, "用户配额已用光"),
    /**
     * 用户端-B级错误码
     */
    CLIENT_B_UPLOAD_FILE_EXCEPTION(10700, "用户上传文件异常"),
    CLIENT_B_UPLOAD_FILE_TYPE_NOT_MATCH(10701, "用户上传文件类型不匹配"),
    CLIENT_B_UPLOAD_FILE_OVER_SIZE(10702, "用户上传文件太大"),
    CLIENT_B_UPLOAD_IMAGE_OVER_SIZE(10703, "用户上传图片太大"),
    CLIENT_B_UPLOAD_VIDEO_OVER_SIZE(10704, "用户上传视频太大"),
    CLIENT_B_UPLOAD_COMPRESSED_FILE_OVER_SIZE(10705, "用户上传压缩文件太大"),

    /**
     * 用户端-B级错误码
     */
    CLIENT_B_VERSION_EXCEPTION(10800, "用户当前版本异常"),
    CLIENT_B_VERSION_NOT_MATCH(10801, "用户安装版本与系统不匹配"),
    CLIENT_B_VERSION_LOW(10802, "用户安装版本过低"),
    CLIENT_B_VERSION_HIGH(10803, "用户安装版本过高"),
    CLIENT_B_VERSION_OVERDUE(10804, "用户安装版本已过期"),
    CLIENT_B_VERSION_REQUEST_NOT_MATCH(10805, "用户1PI请求版本不匹配"),
    CLIENT_B_VERSION_REQUEST_HIGH(10806, "用户1PI请求版本过高"),
    CLIENT_B_VERSION_REQUEST_LOW(10807, "用户1PI请求版本过低"),

    /**
     * 用户端-B级错误码
     */
    CLIENT_B_PRIVACY(10900, "用户隐私未授权"),
    CLIENT_B_PRIVACY_UNSIGNED(10901, "用户隐私未签署"),
    CLIENT_B_PRIVACY_WEBCAM_UNAUTHORIZED(10902, "用户摄像头未授权"),
    CLIENT_B_PRIVACY_CAMERA_UNAUTHORIZED(10903, "用户相机未授权"),
    CLIENT_B_PRIVACY_PHOTO_GALLERY_UNAUTHORIZED(10904, "用户图片库未授权"),
    CLIENT_B_PRIVACY_FILE_UNAUTHORIZED(10905, "用户文件未授权"),
    CLIENT_B_PRIVACY_LOCATION_UNAUTHORIZED(10906, "用户位置信息未授权"),
    CLIENT_B_PRIVACY_ADDRESS_BOOK_UNAUTHORIZED(10907, "用户通讯录未授权"),

    /**
     * 用户端-B级错误码
     */
    CLIENT_B_DEVICE_EXCEPTION(11000, "用户设备异常"),
    CLIENT_B_CAMERA_EXCEPTION(11001, "用户相机异常"),
    CLIENT_B_MICROPHONE_EXCEPTION(11002, "用户麦克风异常"),
    CLIENT_B_TELEPHONE_RECEIVER_EXCEPTION(11003, "用户听筒异常"),
    CLIENT_B_LOUDSPEAKER_EXCEPTION(11004, "用户扬声器异常"),
    CLIENT_B_GPS_EXCEPTION(11005, "用户GPS定位异常"),

    /**
     * 用户端-C级错误码
     */
    CLIENT_C_APPSECURITY_EXCEPTION(12000, "系统安全服务异常"),

    /**
     * 用户端-C级错误码
     */
    CLIENT_C_MASTER_DATA_EXCEPTION(13000, "主数据服务异常"),

    /**
     * 用户端-C级错误码
     */
    CLIENT_C_IMAGE_EXCEPTION(14000, "图片服务异常"),

    /**
     * 用户端-C级错误码
     */
    CLIENT_C_LOG_EXCEPTION(15000, "日志服务异常"),

    /**
     * 用户端-C级错误码
     */
    CLIENT_C_ESOURCING_EXCEPTION(16000, "采购服务异常"),


    /**
     * 系统-A级错误码
     */
    SYSTEM_A_EXECUTE_EXCEPTION(50001, "系统执行出错"),
    /**
     * 系统-B级错误码
     */
    SYSTEM_B_EXECUTE_TIMEOUT(50100, "系统执行超时  "),
    SYSTEM_B_ORDER_HANDLE_TIMEOUT(50101, "系统订单处理超时"),
    /**
     * 系统-B级错误码
     */
    SYSTEM_B_DISASTER_RECOVERY_TRIGGERED(50200, "系统容灾功能被触发"),
    SYSTEM_B_CURRENT_LIMIT(50210, "系统限流"),
    SYSTEM_B_DEGRADE(50220, "系统功能降级"),
    /**
     * 系统-B级错误码
     */
    SYSTEM_B_RESOURCE_EXCEPTION(50300, "系统资源异常"),
    SYSTEM_B_RESOURCE_USED_UP(50310, "系统资源耗尽"),
    SYSTEM_B_RESOURCE_DISK_SPACE_USED_UP(50311, "系统磁盘空间耗尽"),
    SYSTEM_B_RESOURCE_MEMORY_USED_UP(50312, "系统内存耗尽"),
    SYSTEM_B_RESOURCE_FILE_HANDLE_USED_UP(50313, "文件句柄耗尽"),
    SYSTEM_B_RESOURCE_CONNECTION_POOL_USED_UP(50314, "系统连接池耗尽"),
    SYSTEM_B_RESOURCE_THREAD_POOL_USED_UP(50315, "系统线程池耗尽"),
    SYSTEM_B_RESOURCE_ACCESS_EXCEPTION(50320, "系统资源访问异常"),
    SYSTEM_B_RESOURCE_DISK_FILE_READ_FAILURE(50321, "系统读取磁盘文件失败"),

    /**
     * 调用第三方服务-A级错误码
     */

    THIRD_PARTY_SERVICE_A_CALL_EXCEPTION(70001, "调用第三方服务出错"),
    /**
     * 调用第三方服务-B级错误码
     */
    THIRD_PARTY_SERVICE_B_MIDDLEWARE_SERVICE_ERROR(70100, "中间件服务出错  "),
    THIRD_PARTY_SERVICE_B_ERROR(70110, "RP4服务出错"),
    THIRD_PARTY_SERVICE_B_NOT_FOUND(70111, "RP4服务未找到"),
    THIRD_PARTY_SERVICE_B_UNREGISTERED(70112, "RP4服务未注册"),
    THIRD_PARTY_SERVICE_B_INTERFACE_NOT_EXIST(70113, "接口不存在"),
    THIRD_PARTY_SERVICE_B_MSG_SERVICE_ERROR(70120, "消息服务出错"),
    THIRD_PARTY_SERVICE_B_MSG_DELIVERY_ERROR(70121, "消息投递出错"),
    THIRD_PARTY_SERVICE_B_MSG_CONSUME_ERROR(70122, "消息消费出错"),
    THIRD_PARTY_SERVICE_B_MSG_SUBSCRIBE_ERROR(70123, "消息订阅出错"),
    THIRD_PARTY_SERVICE_B_MSG_GROUPING_NOT_FOUND(70124, "消息分组未查到"),
    THIRD_PARTY_SERVICE_B_CACHE_SERVICE_ERROR(70130, "缓存服务出错"),
    THIRD_PARTY_SERVICE_B_KEY_LENGTH_EXCEED_LIMIT(70131, "key长度超过限制"),
    THIRD_PARTY_SERVICE_B_VALUE__LENGTH_EXCEED_LIMIT(70132, "value长度超过限制"),
    THIRD_PARTY_SERVICE_B_STORE_CAPACITY_FULL(70133, "存储容量已满"),
    THIRD_PARTY_SERVICE_B_DATA_FORMAT_NOT_SUPPORT(70134, "不支持的数据格式"),
    THIRD_PARTY_SERVICE_B_CONFIGURATION_SERVICE_ERROR(70140, "配置服务出错"),
    THIRD_PARTY_SERVICE_B_NETWORK_RESOURCE_ERROR(70150, "网络资源服务出错"),
    THIRD_PARTY_SERVICE_B_VPN_SERVICE_ERROR(70151, "VPN服务出错"),
    THIRD_PARTY_SERVICE_B_4DN_SERVICE_ERROR(70152, "4DN服务出错"),
    THIRD_PARTY_SERVICE_B_DOMAIN_PARSING_ERROR(70153, "域名解析服务出错"),
    THIRD_PARTY_SERVICE_B_GATEWAY_ERROR(70154, "网关服务出错"),
    /**
     * 调用第三方服务-B级错误码
     */
    THIRD_PARTY_SERVICE_B_EXECUTE_TIMEOUT(70200, "第三方系统执行超时"),
    THIRD_PARTY_SERVICE_B_RP4_EXECUTE_TIMEOUT(70210, "RP4执行超时"),
    THIRD_PARTY_SERVICE_B_MSG_DELIVERY_TIMEOUT(70220, "消息投递超时"),
    THIRD_PARTY_SERVICE_B_CACHE_SERVICE_TIMEOUT(70230, "缓存服务超时"),
    THIRD_PARTY_SERVICE_B_CONFIGURATION_SERVICE_TIMEOUT(70240, "配置服务超时"),
    THIRD_PARTY_SERVICE_B_DATABASE_SERVICE_TIMEOUT(70250, "数据库服务超时"),
    /**
     * 调用第三方服务-B级错误码
     */
    THIRD_PARTY_SERVICE_B_DB_SERVICE_ERROR(70300, "数据库服务出错"),
    THIRD_PARTY_SERVICE_B_DB_TABLE_NOT_EXIST(70311, "表不存在"),
    THIRD_PARTY_SERVICE_B_DB_COLUMN_NOT_EXIST(70312, "列不存在"),
    THIRD_PARTY_SERVICE_B_DB_DUPLICATE_COLUMN_NAME_WHEN_JOIN(70321, "多表关联中存在多个相同名称的列"),
    THIRD_PARTY_SERVICE_B_DB_DEADLOCK(70331, "数据库死锁"),
    THIRD_PARTY_SERVICE_B_DB_PRIMARY_KEY_CONFLICT(70341, "主键冲突"),
    /**
     * 调用第三方服务-B级错误码
     */
    THIRD_PARTY_SERVICE_B_RECOVERY_TRIGGERED(70400, "第三方容灾系统被触发"),
    THIRD_PARTY_SERVICE_B_CURRENT_LIMIT(70401, "第三方系统限流"),
    THIRD_PARTY_SERVICE_B_DEGRADE(70402, "第三方功能降级"),
    /**
     * 调用第三方服务-B级错误码
     */
    THIRD_PARTY_SERVICE_B_NOTIFY_SERVICE_ERROR(70500, "通知服务出错"),
    THIRD_PARTY_SERVICE_B_NOTIFY_SMS_REMINDER_FAILURE(70501, "短信提醒服务失败"),
    THIRD_PARTY_SERVICE_B_NOTIFY_VOICE_REMINDER_FAILURE(70502, "语音提醒服务失败"),
    THIRD_PARTY_SERVICE_B_NOTIFY_MAIL_REMINDER_FAILURE(70503, "邮件提醒服务失败"),

    ;

    private final int code;
    private final String message;

    ApiCode(final int code, final String message) {
        this.code = code;
        this.message = message;
    }

    public static ApiCode getApiCode(int code) {
        ApiCode[] ecs = ApiCode.values();
        for (ApiCode ec : ecs) {
            if (ec.getCode() == code) {
                return ec;
            }
        }
        return SUCCESS;
    }

    public int getCode() {
        return code;
    }

    public String getMessage() {
        return message;
    }

}
